# general config:
name = "Simple"
example_file = "./top.sv"
trace_file = "trace_simple.pftrace"
# annotated_trace_file =

# compilation/run/annotation config:
files = ["../../include/cspect_pkg.sv", "./top.sv"]
extra_verilator_flags = ["-Wno-TIMESCALEMOD", "+incdir+../../include"]
# annotation_cmd =

# docs:
docs_sort_key = 0
