# general config:
name = "CPU"
example_file = "./top.sv"
trace_file = "trace_cpu.pftrace"
# annotated_trace_file =

# compilation/run/annotation config:
files = ["../../include/cspect_pkg.sv", "./top.sv"]
extra_verilator_flags = ["-Wno-TIMESCALEMOD", "+incdir+../../include"]
# annotation_cmd =

# docs:
docs_sort_key = 5
docs_blurb = """
A very simple 8-bit CPU with a RAM, ROM, and driver/testbench module.

Serves as an example of how CircumSpect can be used to instrument a "proper", hierarchical RTL circuit.
"""
